name: WindowsCRD

on: 
  workflow_dispatch:
    inputs:
  
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
 
    steps:
    - uses: actions/checkout@v2
    - name: Download 
      run: ./setup.ps1
    - name: Setup
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: .
      run: cmd /c wallpaper.bat
    - name: Done
      run: cmd /c wallpaper.bat
    - name: Done
      run: ./loop.ps1
